app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(sidebarTabs = "File")
app$uploadFile(upload = "humboldt_params.rds")
app$setInputs(sidebarTabs = "Species")
app$setInputs(h = 41)
app$setInputs(sp = "Mackerel")
app$snapshot()
app$setInputs(mainTabs = "Biomass")
app$setInputs(speciesParamsTabs = "Other")
app$setInputs(n0 = 78.3)
app$snapshot()
app$setInputs(sp_interact = "click")
app$snapshot()
app$setInputs(mainTabs = "Growth")
app$setInputs(alpha = 0.47)
app$snapshot()
app$setInputs(k_vb = 2)
app$setInputs(t0 = 2)
app$snapshot()
app$setInputs(mainTabs = "Repro")
app$setInputs(ks = 5.25)
app$setInputs(ks = 2.5)
app$setInputs(sp_interact = "click")
app$snapshot()
app$setInputs(mainTabs = "Catch")
# Input '`.clientValue-plotly_relayout-A`' was set, but doesn't have an input binding.
app$setInputs(speciesParamsTabs = "Fishing")
app$setInputs(catchability = 0.1)
app$setInputs(l50 = 9)
app$snapshot()
app$setInputs(sidebarTabs = "File")
app$uploadFile(upload = "../humboldt_params.rds") 
app$snapshot()
