<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>The Trait-Based Model • mizer</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/cerulean/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="The Trait-Based Model">
<meta property="og:description" content="mizer">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">mizer</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">2.0.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/mizer.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li>
  <a href="../articles/index.html">Guides</a>
</li>
<li>
  <a href="../articles/publications.html">Publications</a>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/sizespectrum/mizer/">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>The Trait-Based Model</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/sizespectrum/mizer/blob/master/vignettes/trait_model.Rmd"><code>vignettes/trait_model.Rmd</code></a></small>
      <div class="hidden name"><code>trait_model.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>The trait-based size spectrum model can be derived as a simplification of the general model outline in the <a href="model_description.html">model description</a> section. It is more complicated than a <a href="community_model.html">community model</a> and the most significant difference between the two is that while the community model aggregates all species into a single spectrum, the trait-based model resolves many species.</p>
<p>In a trait-based model the asymptotic size is considered to be the most important <em>trait</em> characterizing a species. Most of the species-specific parameters, such as <span class="math inline">\(\beta\)</span> and <span class="math inline">\(\sigma\)</span>, are the same for all species. Other model parameters are determined by the asymptotic size. For example, the weight at maturation is a fixed fraction of the asymptotic size. The asymptotic sizes of the species are spread evenly on a logarithmic scale. The number of species is not important and does not affect the general dynamics of the model.</p>
</div>
<div id="sec:set_up_trait_model" class="section level2">
<h2 class="hasAnchor">
<a href="#sec:set_up_trait_model" class="anchor"></a>Setting up a trait-based model</h2>
<p>To help set up a trait-based model, there is a wrapper function, <code><a href="../reference/newTraitParams.html">newTraitParams()</a></code>. Like the <code><a href="../reference/newCommunityParams.html">newCommunityParams()</a></code> function described in the section on the <a href="community_model.html">community model</a>, this function can take many arguments. Most of them have default values so you don’t need to worry about them for the moment. See the help page for <code><a href="../reference/newCommunityParams.html">newCommunityParams()</a></code> for more details.</p>
<p>One of the key differences between the community type model and the trait-based model is that reproduction and egg production are considered. In the community model, reproduction is constant and there is no relationship between the abundance in the community and egg production. In the trait-based model, the egg production is dependent on mature individuals investing part of their energy income into reproduction. The relationship between the energy invested into reproduction and the actual rate of egg production is modelled using a <em>Beverton-Holt</em> type function (the default in <code>mizer</code>, see <a href="model_description.html#recruitment">the section on density-dependence in reproduction</a>) where the reproduction rate <span class="math inline">\(R_i\)</span> (numbers per time) approaches a maximum as the energy invested increases.</p>
<p>Here we set up the model to have 10 species, with asymptotic sizes ranging from 10 g to 100 kg. All the other parameters have default values.</p>
<div class="sourceCode" id="cb1"><html><body><pre class="r"><span class="no">params</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/newTraitParams.html">newTraitParams</a></span>(<span class="kw">no_sp</span> <span class="kw">=</span> <span class="fl">10</span>, <span class="kw">min_w_inf</span> <span class="kw">=</span> <span class="fl">10</span>, <span class="kw">max_w_inf</span> <span class="kw">=</span> <span class="fl">1e5</span>)</pre></body></html></div>
<pre><code>## Note: Using f0, h, lambda, kappa and the predation kernel to calculate gamma.</code></pre>
<p>The output reminds the user that <span class="math inline">\(\gamma\)</span> was not specified, and so will be calculated using other parameters.</p>
<p>This function returns an object of type <code>MizerParams</code> that holds all the model information, including species parameters. This object can therefore be interrogated in the same way as described in <a href="community_model.html">the section on the community model</a>.</p>
<div class="sourceCode" id="cb3"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span>(<span class="no">params</span>)</pre></body></html></div>
<pre><code>## An object of class "MizerParams" 
## Consumer size spectrum:
##  minimum size:   0.001
##  maximum size:   1e+05
##  no. size bins:  161
## Resource size spectrum:
##  minimum size:   1e-10
##  maximum size:   2.23872
##  no. size bins:  208 (301 size bins in total)
## Species details:
##    species        w_inf        w_mat beta sigma
## 1        1 8.912509e+00     2.511886  100   1.3
## 2        2 2.511886e+01     7.079458  100   1.3
## 3        3 7.079458e+01    19.952623  100   1.3
## 4        4 1.995262e+02    56.234133  100   1.3
## 5        5 5.623413e+02   158.489319  100   1.3
## 6        6 1.584893e+03   446.683592  100   1.3
## 7        7 4.466836e+03  1258.925412  100   1.3
## 8        8 1.258925e+04  3548.133892  100   1.3
## 9        9 3.548134e+04 10000.000000  100   1.3
## 10      10 1.000000e+05 28183.829313  100   1.3
## Fishing gear details:
##  Gear            Target species
##   knife_edge_gear         1 2 3 4 5 6 7 8 9 10</code></pre>
<p>The summary shows us that now we have 10 species in the model, with asymptotic sizes ranging from <span class="math inline">\(8.9125094\)</span> to <span class="math inline">\(`r max(species_params(params)\)</span>w_inf)`$. The rather strange-looking values for the sizes is due to the fact that the size classes are equally spaced on a logarithmic scale.</p>
<p>The size at maturity (<code>w_mat</code>) is linearly related to the asymptotic size. Each species has the same preferred predator-prey mass ratio parameter values (<code>beta</code> and <code>sigma</code>, see <a href="model_description.html#sec:ppmr">the section on predator/prey mass ratio</a>). There are <span class="math inline">\(161\)</span> size bins in the community and <span class="math inline">\(301\)</span> size bins including the resource spectrum. Ignore the summary section on fishing gear for the moment. This is explained later.</p>
</div>
<div id="sec:running_trait_model" class="section level2">
<h2 class="hasAnchor">
<a href="#sec:running_trait_model" class="anchor"></a>Running the trait-based model</h2>
<p>As with the <a href="community_model.html">community model</a>, we can project the trait-based model through time using the <code><a href="../reference/project.html">project()</a></code> function. Here we project the model for 75 years without any fishing (the <code>effort</code> argument is set to 0). We use the default initial population abundances so there is no need to pass in any initial population values (see <a href="running_a_simulation.html#sec:setting_initial_abundances">the section on setting the initial abundances</a>).</p>
<div class="sourceCode" id="cb5"><html><body><pre class="r"><span class="no">sim</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/project.html">project</a></span>(<span class="no">params</span>, <span class="kw">t_max</span> <span class="kw">=</span> <span class="fl">75</span>, <span class="kw">effort</span> <span class="kw">=</span> <span class="fl">0</span>)</pre></body></html></div>
<p>This results in a <code>MizerSim</code> object that contains the abundances of the community and resource spectra through time, as well as the original <code>MizerParams</code> object. As with the community model, we can get a quick overview of the results of the simulation by calling the <code><a href="https://rdrr.io/r/graphics/plot.html">plot()</a></code> method:</p>
<div class="sourceCode" id="cb6"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(<span class="no">sim</span>)</pre></body></html></div>
<p><img src="trait_model_files/figure-html/plot_comm_sim_2-1.png" width="700"></p>
<p>The summary plot has the same panels as the one generated by the community model, but here you can see that all the species in the community are plotted. The panels show the situation in the final time step of the simulation, apart from the biomass through time plot. As this is a trait-based model where all species fully interact with each other, the predation mortality and feeding level by size is the same for each species. In this simulation we turned fishing off so the fishing mortality is 0. The size-spectra show the abundances at size to be evenly spaced by log of asymptotic size.</p>
</div>
<div id="sec:trophic_cascade_trait_model" class="section level2">
<h2 class="hasAnchor">
<a href="#sec:trophic_cascade_trait_model" class="anchor"></a>Example of a trophic cascade with the trait-based model</h2>
<p>As with the community model, it is possible to use the trait-based model to simulate a trophic cascade. Again, we perform two simulations, one with fishing and one without. We therefore need to consider how fishing gears and selectivity have been set up by the <code><a href="../reference/newTraitParams.html">newTraitParams()</a></code> function.</p>
<p>The default fishing selectivity function is a knife-edge function, which only selects individuals larger than 1000 g. There is also only one fishing gear in operation, and this selects all of the species. You can see this if you call the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> method on the <code>params</code> argument we set up above. At the bottom of the summary there is a section on <em>Fishing gear details</em>. You can see that there is only one gear, called <code>knife_edge_gear</code> and that it selects species 1 to 10. To control the size at which individuals are selected there is a <code>knife_edge_size</code> argument to the <code><a href="../reference/newTraitParams.html">newTraitParams()</a></code> function. This has a default value of 1000 g.</p>
<p>In <code>mizer</code> it is possible to include more than one fishing gear in the model and for different species to be caught by different gears. We will ignore this for now, but will explore it further below when we introduce an industrial fishery to the trait-based model.</p>
<p>To set up the trait-based model to have fishing we set up the <code>MizerParams</code> object in exactly the same way as we did before but here the <code>knife_edge_size</code> argument is explicitly passed in for clarity:</p>
<div class="sourceCode" id="cb7"><html><body><pre class="r"><span class="no">params_knife</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/newTraitParams.html">newTraitParams</a></span>(<span class="kw">no_sp</span> <span class="kw">=</span> <span class="fl">10</span>, <span class="kw">min_w_inf</span> <span class="kw">=</span> <span class="fl">10</span>, <span class="kw">max_w_inf</span> <span class="kw">=</span> <span class="fl">1e5</span>,
    <span class="kw">knife_edge_size</span> <span class="kw">=</span> <span class="fl">1000</span>)</pre></body></html></div>
<pre><code>## Note: Using f0, h, lambda, kappa and the predation kernel to calculate gamma.</code></pre>
<p>First we perform a simulation without fishing in the same way we did above by setting the <code>effort</code> argument to 0:</p>
<div class="sourceCode" id="cb9"><html><body><pre class="r"><span class="no">sim0</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/project.html">project</a></span>(<span class="no">params_knife</span>, <span class="kw">effort</span> <span class="kw">=</span> <span class="fl">0</span>, <span class="kw">t_max</span> <span class="kw">=</span> <span class="fl">75</span>)</pre></body></html></div>
<p>Now we simulate with fishing. Here, we use an effort of 0.75. As mentioned in <a href="community_model.html#sec:trophic_cascade_comm_model">the section on trophic cascades in the community model</a>, the fishing mortality on a species is calculated as the product of effort, catchability and selectivity (see <a href="multispecies_model.html#sec:fishing_gear">the section on fishing gears</a> for more details). Selectivity ranges between 0 (not selected) and 1 (fully selected). The default value of catchability is 1. Therefore, in this simulation the fishing mortality of a fully selected individual is simply equal to the effort. This effort is constant throughout the duration of the simulation (however, mizer does allow variable effort).</p>
<div class="sourceCode" id="cb10"><html><body><pre class="r"><span class="no">sim1</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/project.html">project</a></span>(<span class="no">params_knife</span>, <span class="kw">effort</span> <span class="kw">=</span> <span class="fl">0.75</span>, <span class="kw">t_max</span> <span class="kw">=</span> <span class="fl">75</span>)</pre></body></html></div>
<p>Again, we can plot the summary of the fished community using the default <code><a href="https://rdrr.io/r/graphics/plot.html">plot()</a></code> function. The knife-edge selectivity at 1000 g can be clearly seen in the fishing mortality panel:</p>
<div class="sourceCode" id="cb11"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(<span class="no">sim1</span>)</pre></body></html></div>
<p><img src="trait_model_files/figure-html/plot_trait_fmort-1.png" width="700"></p>
<p>The trophic cascade can be explored by comparing the total abundances of all species at size when the community is fished and unfished. As mentioned above, we obtain the abundances with <code><a href="../reference/N.html">N(sim)</a></code>, which returns a three dimensional array with dimensions time x species x size. Here we have 76 time steps (75 from the simulation plus one which stores the initial population), 10 species and 100 sizes:</p>
<div class="sourceCode" id="cb12"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span>(<span class="fu"><a href="../reference/N.html">N</a></span>(<span class="no">sim0</span>))</pre></body></html></div>
<pre><code>## [1]  76  10 161</code></pre>
<p>As with the community model, we are interested in the relative total abundances by size in the final time step so we use the <code><a href="../reference/finalN.html">finalN()</a></code> function. This gives us a matrix with one row per species and one column per size bin. We sum in each column to get a vector with the total abundance per size bin:</p>
<div class="sourceCode" id="cb14"><html><body><pre class="r"><span class="no">total_abund0</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colSums</a></span>(<span class="fu"><a href="../reference/finalN.html">finalN</a></span>(<span class="no">sim0</span>))
<span class="no">total_abund1</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colSums</a></span>(<span class="fu"><a href="../reference/finalN.html">finalN</a></span>(<span class="no">sim1</span>))</pre></body></html></div>
<p>We can then use these vectors to calculate the relative abundances:</p>
<div class="sourceCode" id="cb15"><html><body><pre class="r"><span class="no">relative_abundance</span> <span class="kw">&lt;-</span> <span class="no">total_abund1</span> / <span class="no">total_abund0</span></pre></body></html></div>
<p>This can be plotted using the commands below:</p>
<div class="sourceCode" id="cb16"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="fu"><a href="../reference/w.html">w</a></span>(<span class="no">params</span>), <span class="kw">y</span> <span class="kw">=</span> <span class="no">relative_abundance</span>, <span class="kw">log</span> <span class="kw">=</span> <span class="st">"xy"</span>, <span class="kw">type</span> <span class="kw">=</span> <span class="st">"n"</span>,
     <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Size (g)"</span>, <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Relative abundance"</span>, <span class="kw">ylim</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0.1</span>, <span class="fl">10</span>))
<span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="fu"><a href="../reference/w.html">w</a></span>(<span class="no">params</span>), <span class="kw">y</span> <span class="kw">=</span> <span class="no">relative_abundance</span>)
<span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span>(<span class="fu"><a href="../reference/w.html">w</a></span>(<span class="no">params</span>)), <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span>(<span class="fu"><a href="../reference/w.html">w</a></span>(<span class="no">params</span>))), <span class="kw">y</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">1</span>, <span class="fl">1</span>), <span class="kw">lty</span> <span class="kw">=</span> <span class="fl">2</span>)</pre></body></html></div>
<p><img src="trait_model_files/figure-html/plot_relative_comm_abund2-1.png" width="700"></p>
<p>The impact of fishing on species larger than 1000 g can be clearly seen. The fishing pressure lowers the abundance of large fish (<span class="math inline">\(&gt; 1000\)</span> g). This then relieves the predation pressure on their smaller prey (the preferred predator-prey size ratio is given by the <span class="math inline">\(\beta\)</span> parameter, which is set to 100 by default), leading to an increase in their abundance. This in turn increases the predation mortality on their smaller prey, which reduces their abundance and so on.</p>
<p>This impact can also be seen by looking at the predation mortality by size. The predation mortalities are retrieved using the <code><a href="../reference/getPredMort.html">getPredMort()</a></code> function. As mentioned above, for the trait based model the predation mortality by size is the same for each species. Therefore we only look at the predation mortality of the first species.</p>
<div class="sourceCode" id="cb17"><html><body><pre class="r"><span class="no">m2_no_fishing</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/getPredMort.html">getPredMort</a></span>(<span class="no">params</span>, <span class="fu"><a href="../reference/finalN.html">finalN</a></span>(<span class="no">sim0</span>))[<span class="fl">1</span>, ]
<span class="no">m2_with_fishing</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/getPredMort.html">getPredMort</a></span>(<span class="no">params</span>, <span class="fu"><a href="../reference/finalN.html">finalN</a></span>(<span class="no">sim1</span>))[<span class="fl">1</span>, ]</pre></body></html></div>
<p>The predation mortalities can then be plotted.</p>
<div class="sourceCode" id="cb18"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="fu"><a href="../reference/w.html">w</a></span>(<span class="no">params</span>), <span class="kw">y</span> <span class="kw">=</span> <span class="no">m2_with_fishing</span>, <span class="kw">log</span> <span class="kw">=</span> <span class="st">"x"</span>, <span class="kw">type</span> <span class="kw">=</span> <span class="st">"n"</span>,
     <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Size [g]"</span>, <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Predation Mortality [1/year]"</span>)
<span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="fu"><a href="../reference/w.html">w</a></span>(<span class="no">params</span>), <span class="kw">y</span> <span class="kw">=</span> <span class="no">m2_no_fishing</span>, <span class="kw">lty</span> <span class="kw">=</span> <span class="fl">2</span>)
<span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="fu"><a href="../reference/w.html">w</a></span>(<span class="no">params</span>), <span class="kw">y</span> <span class="kw">=</span> <span class="no">m2_with_fishing</span>)</pre></body></html></div>
<div class="figure">
<img src="trait_model_files/figure-html/plot_relative_trait_m2-1.png" alt="Predation mortalities from the unfished (dashed line) and fished (solid line) trait-based model." width="700"><p class="caption">
Predation mortalities from the unfished (dashed line) and fished (solid line) trait-based model.
</p>
</div>
</div>
<div id="sec:trait_additional_gear" class="section level2">
<h2 class="hasAnchor">
<a href="#sec:trait_additional_gear" class="anchor"></a>Setting up an industrial fishing gear</h2>
<p>In this section we want to operate an <em>industrial</em> fishery. Industrial fishing targets the small zooplanktivorous species that are typically used for fishmeal production.</p>
<p>In the previous simulations we had only one fishing gear and it targeted all the species in the community. This gear had a knife-edge selectivity that only selected species larger than 1 kg. We can see that when we look at the gear parameters</p>
<div class="sourceCode" id="cb19"><html><body><pre class="r"><span class="fu"><a href="../reference/setFishing.html">gear_params</a></span>(<span class="no">params</span>)</pre></body></html></div>
<pre><code>##               gear species   sel_func knife_edge_size catchability
## 1  knife_edge_gear       1 knife_edge            1000            1
## 2  knife_edge_gear       2 knife_edge            1000            1
## 3  knife_edge_gear       3 knife_edge            1000            1
## 4  knife_edge_gear       4 knife_edge            1000            1
## 5  knife_edge_gear       5 knife_edge            1000            1
## 6  knife_edge_gear       6 knife_edge            1000            1
## 7  knife_edge_gear       7 knife_edge            1000            1
## 8  knife_edge_gear       8 knife_edge            1000            1
## 9  knife_edge_gear       9 knife_edge            1000            1
## 10 knife_edge_gear      10 knife_edge            1000            1</code></pre>
<p>We will expand the model to include multiple fishing gears. This requires us to look more closely at how fishing gears are handled in <code>mizer</code>. In <code>mizer</code> it is possible for a fishing gear to catch only a subset of the species in the model. This is useful because when running a simulation with <code><a href="../reference/project.html">project()</a></code> you can specify the effort per gear and so you can turn gears on or off as you want. Each gear has a selectivity curve for each species.</p>
<p>We will set up the model to include two fishing gears: an <code>industrial</code> gear that only catches species with an asymptotic size less than or equal to 500g, and a second gear, <code>other</code>, that catches everything else. The position of the knife-edge for both gears will occur at 0.05 x the asymptotic size i.e. the selectivity parameters will be different for each species and will depend on the asymptotic size.</p>
<p>For this we will need to change the <code>gear_params</code> data frame. If we want to keep the original model, we should first make a copy before making modifications.</p>
<div class="sourceCode" id="cb21"><html><body><pre class="r"><span class="no">params_multi_gear</span> <span class="kw">&lt;-</span> <span class="no">params</span></pre></body></html></div>
<p>To start with we need to know what the asymptotic sizes of the species in the model are so we can determine the knife-edge positions for each species. These are stored in the <code>w_inf</code> column of the <code>species_params</code> data frame inside the <code>params</code> object. We can then use these asymptotic sizes to set a vector of knife edge sizes that are 0.05 times the asymptotic size:</p>
<div class="sourceCode" id="cb22"><html><body><pre class="r"><span class="fu"><a href="../reference/setFishing.html">gear_params</a></span>(<span class="no">params_multi_gear</span>)$<span class="no">knife_edge_size</span> <span class="kw">&lt;-</span>
  <span class="fu"><a href="../reference/setParams.html">species_params</a></span>(<span class="no">params</span>)$<span class="no">w_inf</span> * <span class="fl">0.05</span></pre></body></html></div>
<p>Now we want to assign each species to either the <em>industrial</em> or <em>other</em> gear.</p>
<div class="sourceCode" id="cb23"><html><body><pre class="r"><span class="no">no_sp</span> <span class="kw">&lt;-</span> <span class="fl">10</span>
<span class="no">gear</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="st">"Industrial"</span>, <span class="no">no_sp</span>)
<span class="no">gear</span>[<span class="fu"><a href="../reference/setParams.html">species_params</a></span>(<span class="no">params</span>)$<span class="no">w_inf</span> <span class="kw">&gt;</span> <span class="fl">500</span>] <span class="kw">&lt;-</span> <span class="st">"Other"</span>
<span class="fu"><a href="../reference/setFishing.html">gear_params</a></span>(<span class="no">params_multi_gear</span>)$<span class="no">gear</span> <span class="kw">&lt;-</span> <span class="no">gear</span></pre></body></html></div>
<p>To check what has just happened let us look at the new gear parameter data frame:</p>
<div class="sourceCode" id="cb24"><html><body><pre class="r"><span class="fu"><a href="../reference/setFishing.html">gear_params</a></span>(<span class="no">params_multi_gear</span>)</pre></body></html></div>
<pre><code>##          gear species   sel_func knife_edge_size catchability
## 1  Industrial       1 knife_edge       0.4456255            1
## 2  Industrial       2 knife_edge       1.2559432            1
## 3  Industrial       3 knife_edge       3.5397289            1
## 4  Industrial       4 knife_edge       9.9763116            1
## 5       Other       5 knife_edge      28.1170663            1
## 6       Other       6 knife_edge      79.2446596            1
## 7       Other       7 knife_edge     223.3417961            1
## 8       Other       8 knife_edge     629.4627059            1
## 9       Other       9 knife_edge    1774.0669462            1
## 10      Other      10 knife_edge    5000.0000000            1</code></pre>
<p>Having created our <code>MizerParams</code> object with multiple gears, we can now turn our attention to running a projection with multiple gears. In our previous examples of calling <code><a href="../reference/project.html">project()</a></code> we have specified the fishing effort with the <code>effort</code> argument using a single value. This fixes the fishing effort for all gears in the model, for all time steps. We can do this with our multi-gear parameter object:</p>
<div class="sourceCode" id="cb26"><html><body><pre class="r"><span class="no">sim_multi_gear</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/project.html">project</a></span>(<span class="no">params_multi_gear</span>, <span class="kw">t_max</span> <span class="kw">=</span> <span class="fl">75</span>, <span class="kw">effort</span> <span class="kw">=</span> <span class="fl">0.5</span>)</pre></body></html></div>
<p>By plotting this you can see that the fishing mortality for each species now has a different selectivity pattern, and that the position of the selectivity knife-edge is given by the asymptotic size of the species.</p>
<div class="sourceCode" id="cb27"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(<span class="no">sim_multi_gear</span>)</pre></body></html></div>
<p><img src="trait_model_files/figure-html/plot_multi_gear_trait_single_effort-1.png" width="700"></p>
<p>For the industrial fishery we said that we only wanted species with an asymptotic size of 500 g or less to be fished. There are several ways of specifying the <code>effort</code> argument for <code><a href="../reference/project.html">project()</a></code> . Above we specified a single value that was used for all gears, for all time steps. It is also possible to specify a separate effort for each gear that will be used for all time steps. To do this we pass in effort as a named vector. Here we set the effort for the <em>Industrial</em> gear to 0.75, and the effort of the <em>Other</em> gear to 0 (effectively turning it off).</p>
<div class="sourceCode" id="cb28"><html><body><pre class="r"><span class="no">sim_multi_gear</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/project.html">project</a></span>(<span class="no">params_multi_gear</span>, <span class="kw">t_max</span> <span class="kw">=</span> <span class="fl">75</span>,
    <span class="kw">effort</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="kw">Industrial</span> <span class="kw">=</span> <span class="fl">0.75</span>, <span class="kw">Other</span> <span class="kw">=</span> <span class="fl">0</span>))</pre></body></html></div>
<p>Now you can see that the <em>Industrial</em> gear has been operating and that fishing mortality for species larger than 500 g is 0.</p>
<div class="sourceCode" id="cb29"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(<span class="no">sim_multi_gear</span>)</pre></body></html></div>
<p><img src="trait_model_files/figure-html/plot_multi_gear_trait-1.png" width="700"></p>
</div>
<div id="the-impact-of-industrial-fishing" class="section level2">
<h2 class="hasAnchor">
<a href="#the-impact-of-industrial-fishing" class="anchor"></a>The impact of industrial fishing</h2>
<p>In the previous section we set up and ran a model in which an industrial fishery was operating that only selected smaller species. We can now answer the question: what is the impact of such a fishery? We can again compare abundances of the fished (<code>sim_industrial1</code>) and unfished (<code>sim_industrial0</code>) cases:</p>
<div class="sourceCode" id="cb30"><html><body><pre class="r"><span class="no">sim_industrial0</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/project.html">project</a></span>(<span class="no">params_multi_gear</span>, <span class="kw">t_max</span> <span class="kw">=</span> <span class="fl">75</span>, <span class="kw">effort</span> <span class="kw">=</span> <span class="fl">0</span>)
<span class="no">sim_industrial1</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/project.html">project</a></span>(<span class="no">params_multi_gear</span>, <span class="kw">t_max</span> <span class="kw">=</span> <span class="fl">75</span>,
    <span class="kw">effort</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="kw">Industrial</span> <span class="kw">=</span> <span class="fl">0.75</span>, <span class="kw">Other</span> <span class="kw">=</span> <span class="fl">0</span>))
<span class="no">total_abund0</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span>(<span class="fu"><a href="../reference/finalN.html">finalN</a></span>(<span class="no">sim_industrial0</span>), <span class="fl">2</span>, <span class="no">sum</span>)
<span class="no">total_abund1</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span>(<span class="fu"><a href="../reference/finalN.html">finalN</a></span>(<span class="no">sim_industrial1</span>), <span class="fl">2</span>, <span class="no">sum</span>)
<span class="no">relative_abundance</span> <span class="kw">&lt;-</span> <span class="no">total_abund1</span> / <span class="no">total_abund0</span></pre></body></html></div>
<p>And plot the relative abundances:</p>
<div class="sourceCode" id="cb31"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="fu"><a href="../reference/w.html">w</a></span>(<span class="no">params</span>), <span class="kw">y</span> <span class="kw">=</span> <span class="no">relative_abundance</span>, <span class="kw">log</span> <span class="kw">=</span> <span class="st">"xy"</span>, <span class="kw">type</span> <span class="kw">=</span> <span class="st">"n"</span>,
     <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Size [g]"</span>, <span class="kw">ylab</span><span class="kw">=</span><span class="st">"Relative abundance"</span>, <span class="kw">ylim</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0.1</span>, <span class="fl">10</span>))
<span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="fu"><a href="../reference/w.html">w</a></span>(<span class="no">params</span>), <span class="kw">y</span> <span class="kw">=</span> <span class="no">relative_abundance</span>)
<span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span>(<span class="fu"><a href="../reference/w.html">w</a></span>(<span class="no">params</span>)),<span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span>(<span class="fu"><a href="../reference/w.html">w</a></span>(<span class="no">params</span>))), <span class="kw">y</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">1</span>, <span class="fl">1</span>), <span class="kw">lty</span> <span class="kw">=</span> <span class="fl">2</span>)</pre></body></html></div>
<p><img src="trait_model_files/figure-html/plot_relative_comm_abund_industrial-1.png" width="700"></p>
<p>This shows another trophic cascade, although this time one driven by fishing the species at the midrange part of the spectrum, not the largest individuals as before. This trophic cascade acts in both directions. The cascade upwards is driven by the lack of food for predators leading to smaller realised maximum sizes. The cascade downwards has the same mechanism as fishing on large fish, a combination of predation mortality and food limitation.</p>
<p>The next section explains how to setup the more general <a href="multispecies_model.html">multispecies model.</a></p>
</div>
  </div>

  <div class="col-md-3 hidden-xs" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by <a href="https://www.york.ac.uk/maths/staff/gustav-delius/">Gustav Delius</a>, Finlay Scott, <a href="http://www.utas.edu.au/profiles/staff/imas/julia-blanchard">Julia Blanchard</a>, <a href="https://ken.haste.dk/">Ken Andersen</a>.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.5.0.9000.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
